import './globals.css'
import type { Metadata } from 'next'
import { Providers } from './provider'
import { Inter } from 'next/font/google';
import Header from '@/app/home/Header';
import Footer from './home/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <main style={{ height: 'calc(100% - 120px)', overflow: 'auto' }}>
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
